/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2016-01-08 at 07:07:44 UTC 
 * Modify at your own risk.
 */

package com.appspot.captest_1180.alerts.model;

/**
 * Model definition for CAPAlert.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the alerts. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CAPAlert extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String areaDesc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String author;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String category;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String certainty;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime effective;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String event;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime expires;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> fipslist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String link;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String msgType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CAPGeoPtMessage> polygon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime published;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String severity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String summary;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> ugclist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime updated;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String urgency;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String vtec;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAreaDesc() {
    return areaDesc;
  }

  /**
   * @param areaDesc areaDesc or {@code null} for none
   */
  public CAPAlert setAreaDesc(java.lang.String areaDesc) {
    this.areaDesc = areaDesc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthor() {
    return author;
  }

  /**
   * @param author author or {@code null} for none
   */
  public CAPAlert setAuthor(java.lang.String author) {
    this.author = author;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategory() {
    return category;
  }

  /**
   * @param category category or {@code null} for none
   */
  public CAPAlert setCategory(java.lang.String category) {
    this.category = category;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCertainty() {
    return certainty;
  }

  /**
   * @param certainty certainty or {@code null} for none
   */
  public CAPAlert setCertainty(java.lang.String certainty) {
    this.certainty = certainty;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getEffective() {
    return effective;
  }

  /**
   * @param effective effective or {@code null} for none
   */
  public CAPAlert setEffective(com.google.api.client.util.DateTime effective) {
    this.effective = effective;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEvent() {
    return event;
  }

  /**
   * @param event event or {@code null} for none
   */
  public CAPAlert setEvent(java.lang.String event) {
    this.event = event;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getExpires() {
    return expires;
  }

  /**
   * @param expires expires or {@code null} for none
   */
  public CAPAlert setExpires(com.google.api.client.util.DateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getFipslist() {
    return fipslist;
  }

  /**
   * @param fipslist fipslist or {@code null} for none
   */
  public CAPAlert setFipslist(java.util.List<java.lang.String> fipslist) {
    this.fipslist = fipslist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public CAPAlert setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLink() {
    return link;
  }

  /**
   * @param link link or {@code null} for none
   */
  public CAPAlert setLink(java.lang.String link) {
    this.link = link;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMsgType() {
    return msgType;
  }

  /**
   * @param msgType msgType or {@code null} for none
   */
  public CAPAlert setMsgType(java.lang.String msgType) {
    this.msgType = msgType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<CAPGeoPtMessage> getPolygon() {
    return polygon;
  }

  /**
   * @param polygon polygon or {@code null} for none
   */
  public CAPAlert setPolygon(java.util.List<CAPGeoPtMessage> polygon) {
    this.polygon = polygon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getPublished() {
    return published;
  }

  /**
   * @param published published or {@code null} for none
   */
  public CAPAlert setPublished(com.google.api.client.util.DateTime published) {
    this.published = published;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSeverity() {
    return severity;
  }

  /**
   * @param severity severity or {@code null} for none
   */
  public CAPAlert setSeverity(java.lang.String severity) {
    this.severity = severity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public CAPAlert setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSummary() {
    return summary;
  }

  /**
   * @param summary summary or {@code null} for none
   */
  public CAPAlert setSummary(java.lang.String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public CAPAlert setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getUgclist() {
    return ugclist;
  }

  /**
   * @param ugclist ugclist or {@code null} for none
   */
  public CAPAlert setUgclist(java.util.List<java.lang.String> ugclist) {
    this.ugclist = ugclist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getUpdated() {
    return updated;
  }

  /**
   * @param updated updated or {@code null} for none
   */
  public CAPAlert setUpdated(com.google.api.client.util.DateTime updated) {
    this.updated = updated;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrgency() {
    return urgency;
  }

  /**
   * @param urgency urgency or {@code null} for none
   */
  public CAPAlert setUrgency(java.lang.String urgency) {
    this.urgency = urgency;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVtec() {
    return vtec;
  }

  /**
   * @param vtec vtec or {@code null} for none
   */
  public CAPAlert setVtec(java.lang.String vtec) {
    this.vtec = vtec;
    return this;
  }

  @Override
  public CAPAlert set(String fieldName, Object value) {
    return (CAPAlert) super.set(fieldName, value);
  }

  @Override
  public CAPAlert clone() {
    return (CAPAlert) super.clone();
  }

}
