application: captest-1180
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /data\.cgi
  script: data.app

- url: /_ah/spi/.*
  script: endpoint.APPLICATION

- url: .*
  script: main.app
  secure: always
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: "1.0"

builtins:
- appstats: on
